import json
import os
import sys
import time
import random
import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm
from openai import OpenAI

# 添加项目根目录到 sys.path
sys.path.append(os.path.join(os.path.dirname(__file__), "../../"))
from classifier.gen_sliver.preprocess_utils import load_json, save_json

# --- 配置区域 ---
DOMAINS = [
    "医疗药物与诊断 (Medical Diagnosis & Pharmacology)",
    "IT技术支持与报错代码 (IT Support & Error Codes)",
    "法律条款与合规性 (Legal Compliance & Statutes)",
    "金融市场与宏观经济 (Financial Markets & Economics)",
    "流行文化与历史事件 (Pop Culture & History)"
]

# 定义不同策略的生成 Prompt
PROMPTS = {
    "S3": """
# Role
你是一个数据合成专家。我们需要为 RAG 系统生成“高精准度匹配”的测试查询。
当前关注领域：{domain}

# Task
请生成 20 条必须使用 **S3 (SPLADE 稀疏检索)** 策略的复杂查询。

# Context & Constraints
1. **策略定义**：S3 侧重于关键词的精确匹配，而非语义相关性。
2. **适用场景**：查询中包含极易混淆的**特定实体**（如具体型号、错误代码、化学式、罕见人名）。
3. **噪声风险**：如果使用向量检索（Dense Retrieval），模型会被语义相似的文档误导（例如用户问 "iPhone 14 Plus"，向量检索可能找回 "iPhone 14 Pro" 的评测，这就是噪声）。

# Output Format
JSON List:
[
  {{
    "query": "...",
    "strategy": "S3",
    "noise_analysis": "需要精确匹配实体 X，防止被 Y 混淆...",
    "reasoning": "由于查询包含精确的非语义符号..."
  }}
]
只输出 JSON 对象，不要包含 markdown 格式。
""",
    "S4_M4": """
# Role
数据合成专家。
当前关注领域：{domain}

# Task
请生成 20 条必须使用 **S4 (混合检索+重排)** 或 **M4 (多跳混合检索)** 的高难度查询。请随机混合生成 S4 和 M4 的例子。

# Context & Constraints
1. **策略定义**：S4/M4 结合了关键词匹配和语义检索，并必须经过 Cross-Encoder 重排序。
2. **适用场景**：
   - **多视角冲突**：问题涉及争议性话题，不同文档可能有冲突观点。
   - **实体比较**：问“A和B的区别”，需要同时找回A和B的文档。
   - **长尾/模糊查询**：查询意图不明确，单一检索方式召回率低。
3. **噪声风险**：单路检索（如只用 BM25）会漏掉重要信息；只用向量检索会引入大量不相关的“幻觉”文档。必须通过 Rerank 机制过滤掉 90% 的噪声。

# Output Format
JSON List:
[
  {{
    "query": "...",
    "strategy": "S4", // 或者 "M4"
    "noise_analysis": "单一检索无法覆盖 A 和 B 两个方面，且容易引入...",
    "reasoning": "问题涉及跨文档对比，需要高召回率配合重排序..."
  }}
]
只输出 JSON 对象，不要包含 markdown 格式。
""",
    "M2": """
# Role
数据合成专家。
当前关注领域：{domain}

# Task
请生成 20 条适合 **M2 (密集向量检索 + 多跳推理)** 的查询。

# Context & Constraints
1. **策略定义**：问题不能通过关键词直接搜到（Keyword Mismatch），必须依靠向量（Embedding）理解隐含意图。
2. **适用场景**：描述性问题、隐喻性问题、或者不知道具体实体名称的搜索。
3. **噪声风险**：关键词检索（S1/S3）完全失效（找不到文档）；需要向量检索捕捉“意思”，但需要 LLM 进行多步推断。

# Output Format
JSON List:
[
  {{
    "query": "...",
    "strategy": "M2",
    "noise_analysis": "关键词无法匹配...",
    "reasoning": "问题描述比较隐晦，需要语义理解..."
  }}
]
只输出 JSON 对象，不要包含 markdown 格式。
"""
}

def generate_batch(client, model, prompt_key, domain):
    """调用 LLM 生成一批数据，带重试机制"""
    prompt_template = PROMPTS[prompt_key]
    prompt = prompt_template.format(domain=domain)
    
    max_retries = 3
    base_delay = 2

    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": "You are a helpful assistant designed to output JSON list."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.8, # 稍微增加温度以提高多样性
                response_format={"type": "json_object"}
            )
            content = response.choices[0].message.content
            
            # 简单的清洗
            if "```json" in content:
                content = content.replace("```json", "").replace("```", "")
            
            data = json.loads(content)
            
            # 兼容有时候模型返回 {"items": [...]} 或者直接 [...] 
            if isinstance(data, dict):
                for k, v in data.items():
                    if isinstance(v, list):
                        return v
                return [] # 没找到 list
            elif isinstance(data, list):
                return data
            else:
                return []

        except Exception as e:
            print(f"Error generating batch for {prompt_key} in {domain} (Attempt {attempt+1}/{max_retries}): {e}")
            if attempt < max_retries - 1:
                time.sleep(base_delay * (attempt + 1)) # 指数退避
            else:
                return []

def transform_to_schema(raw_item, index, strategy_prefix):
    """将生成的简化数据转换为项目标准格式"""
    
    # 提取生成的 strategy，如果没有则使用前缀
    strategy = raw_item.get('strategy', strategy_prefix).upper()
    
    # 构造符合 label_augmented.json 的结构
    new_item = {
        "id": f"syn_{strategy.lower()}_{int(time.time())}_{index}",
        "question": raw_item.get('query'),
        "answer": strategy, # 这里的 answer 在你的逻辑里就是 strategy label
        "recommended_strategy": strategy,
        "complexity_analysis": {
            "reasoning": raw_item.get('reasoning', 'Generated by targeted synthesis.'),
            "noise_risk": raw_item.get('noise_analysis', 'High noise risk identified.')
        },
        "search_intent": f"Targeted synthesis for {strategy}",
        "rationale": raw_item.get('reasoning', 'Generated rationale.')
    }
    return new_item

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_file", type=str, default="classifier/data/label_augmented.json")
    parser.add_argument("--output_file", type=str, default="classifier/data/label_balanced.json")
    parser.add_argument("--model", type=str, default="gpt-4o")
    parser.add_argument("--workers", type=int, default=5)
    args = parser.parse_args()

    # 路径处理
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../"))
    if not os.path.isabs(args.input_file):
        args.input_file = os.path.join(project_root, args.input_file)
    if not os.path.isabs(args.output_file):
        args.output_file = os.path.join(project_root, args.output_file)

    # 初始化 OpenAI
    api_key = os.getenv("OPENAI_API_KEY") or "sk-BZQdNZeSwyih3TKpD95fDd83A90e4556A95f7eB7D489C36b"
    base_url = os.getenv("OPENAI_BASE_URL") or "https://api.gpt.ge/v1/"
    client = OpenAI(api_key=api_key, base_url=base_url)

    print(f"Loading existing data from {args.input_file}...")
    try:
        existing_data = load_json(args.input_file)
    except Exception:
        print("Input file not found, starting fresh.")
        existing_data = []

    print(f"Current count: {len(existing_data)}")

    # 定义生成任务计划
    # 目标：S3 +120, S4/M4 +120, M2 +80 = 总计约 320 条新数据
    tasks = []
    
    # S3 任务 (6轮 x 20条 = 120)
    for i in range(6):
        domain = DOMAINS[i % len(DOMAINS)]
        tasks.append(("S3", domain))
    
    # S4/M4 任务 (6轮 x 20条 = 120)
    for i in range(6):
        domain = DOMAINS[i % len(DOMAINS)]
        tasks.append(("S4_M4", domain))

    # M2 任务 (4轮 x 20条 = 80)
    for i in range(4):
        domain = DOMAINS[i % len(DOMAINS)]
        tasks.append(("M2", domain))

    new_items = []
    print(f"Starting generation with {len(tasks)} tasks using {args.workers} workers...")

    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {executor.submit(generate_batch, client, args.model, task[0], task[1]): task for task in tasks}
        
        for future in tqdm(as_completed(futures), total=len(tasks)):
            task_type, domain = futures[future]
            batch_results = future.result()
            
            if batch_results:
                for idx, item in enumerate(batch_results):
                    processed_item = transform_to_schema(item, len(new_items) + idx, task_type)
                    if processed_item['question'] and processed_item['answer']:
                        new_items.append(processed_item)

    print(f"Generated {len(new_items)} new synthetic samples.")

    # 合并数据
    final_data = existing_data + new_items
    
    # 简单的 M3 -> M4 清洗 (可选，根据你的建议)
    # 如果 M3 数量极少，将其归类为 M4，避免模型学不到
    m3_count = sum(1 for item in final_data if item['answer'] == 'M3')
    if m3_count < 10:
        print(f"Warning: M3 count is very low ({m3_count}). Remapping M3 to M4...")
        for item in final_data:
            if item['answer'] == 'M3':
                item['answer'] = 'M4'
                item['recommended_strategy'] = 'M4'

    # 打印最终分布
    print("\nNew Label Distribution:")
    from collections import Counter
    counts = Counter([item['answer'] for item in final_data])
    total = len(final_data)
    print(f"{'Label':<10} | {'Count':<8} | {'Percentage':<10}")
    print("-" * 35)
    for label in sorted(counts.keys()):
        print(f"{label:<10} | {counts[label]:<8} | {counts[label]/total:.2%}")
    print("-" * 35)

    save_json(args.output_file, final_data)
    print(f"Saved balanced dataset to {args.output_file}")

if __name__ == "__main__":
    main()
